#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# rororo documentation build configuration file, created by
# sphinx-quickstart on Sun May 14 20:32:17 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import datetime
import re
import sys
from pathlib import Path


ROOT_PATH = Path(__file__).parent.parent
SRC_PATH = ROOT_PATH / "src"
sys.path.insert(0, str(SRC_PATH))

PROJECT = "rororo"
INIT_PY = (SRC_PATH / PROJECT / "__init__.py").read_text()
AUTHOR = re.findall('__author__ = "([^"]+)"', INIT_PY)[0]
VERSION = re.findall('__version__ = "([^"]+)"', INIT_PY)[0]
TODAY = datetime.date.today()


extensions = [
    "alabaster",
    "sphinx.ext.autodoc",
    "sphinx_autodoc_typehints",
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
source_suffix = ".rst"
master_doc = "index"

project = PROJECT
author = AUTHOR
copyright = f"2017-{TODAY.year}, {AUTHOR}"

version = ".".join(VERSION.split(".")[:2])
release = VERSION

language = "en"
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
pygments_style = "sphinx"

html_theme = "alabaster"
html_theme_options = {
    "logo_name": True,
    "description": "aiohttp.web OpenAPI 3 schema first server applications",
    "github_user": "playpauseandstop",
    "github_repo": project,
    "github_banner": True,
    "github_button": True,
    "github_type": "star",
    "fixed_sidebar": True,
}
html_static_path = ["_static"]
html_sidebars = {"**": ["about.html", "localtoc.html", "searchbox.html"]}

htmlhelp_basename = "rororodoc"
latex_elements = {}
latex_documents = [
    (
        master_doc,
        "rororo.tex",
        "rororo Documentation",
        "Igor Davydenko",
        "manual",
    )
]

man_pages = [(master_doc, "rororo", "rororo Documentation", [author], 1)]

texinfo_documents = [
    (
        master_doc,
        "rororo",
        "rororo Documentation",
        author,
        "rororo",
        "One line description of project.",
        "Miscellaneous",
    )
]

intersphinx_mapping = {
    "https://docs.python.org/3/": None,
    "https://docs.aiohttp.org/en/stable/": None,
    "https://aiohttp-middlewares.readthedocs.io/en/stable/": None,
    "https://pyrsistent.readthedocs.io/en/stable/": None,
}
