openapi: "3.0.2"

info:
  title: "Hobotnica API"
  description: |
    Reduced Hobotnica API schema as rororo example app.
  version: "1.0.0"
  contact:
    name: "Igor Davydenko (developer)"
    url: "https://igordavydenko.com"
    email: "iam@igordavydenko.com"
  license:
    name: "BSD-3-Clause"
    url: "https://opensource.org/licenses/BSD-3-Clause"

servers:
  - url: "/api"

x-default-responses: &default_responses
  "422":
    $ref: "#/components/responses/ValidationError"
  default:
    $ref: "#/components/responses/DefaultResponse"

paths:
  "/repositories":
    get:
      operationId: "list_repositories"
      tags: ["repositories"]
      summary: "List user repositories registered in Hobotnica."
      parameters:
        - $ref: "#/components/parameters/GitHubUsername"
      responses:
        <<: *default_responses
        "200":
          description: "Available repositories."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Repository"
      security:
        - jwt: []
        - personalToken: []

    post:
      operationId: "create_repository"
      tags: ["repositories"]
      summary: "Add new user repository to Hobotnica."
      parameters:
        - $ref: "#/components/parameters/GitHubUsername"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewRepository"
      responses:
        <<: *default_responses
        "201":
          description: "Added repository details."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Repository"
      security:
        - personalToken: []

  "/repositories/{owner}":
    get:
      operationId: "list_owner_repositories"
      tags: ["repositories"]
      summary: "List repositories owned by user."
      parameters:
        - $ref: "#/components/parameters/RepositoryOwner"
      responses:
        <<: *default_responses
        "200":
          description: "Repositories list."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Repository"
      security:
        - basic: []

  "/repositories/{owner}/env":
    get:
      operationId: "retrieve_owner_env"
      tags: ["environment"]
      summary: "Retrieve common environment vars for user."
      parameters:
        - $ref: "#/components/parameters/RepositoryOwner"
      responses:
        <<: *default_responses
        "200":
          description: "Owner environment vars."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnyObject"
      security:
        - basic: []

  "/repositories/{owner}/{name}":
    get:
      operationId: "retrieve_repository"
      tags:
        - "repositories"
      summary: "Retrieve details of user repository."
      parameters:
        - $ref: "#/components/parameters/GitHubUsername"
        - $ref: "#/components/parameters/RepositoryOwner"
        - $ref: "#/components/parameters/RepositoryName"
      responses:
        <<: *default_responses
        "200":
          description: "Repository details."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Repository"
      security:
        - jwt: []
          personalToken: []

  "/repositories/{owner}/{name}/env":
    get:
      operationId: "retrieve_repository_env"
      tags:
        - "environment"
      summary: "Retrieve common env vars for the repository"
      parameters:
        - $ref: "#/components/parameters/GitHubUsername"
        - $ref: "#/components/parameters/RepositoryOwner"
        - $ref: "#/components/parameters/RepositoryName"
      responses:
        <<: *default_responses
        "200":
          description: "Repository environment vars."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnyObject"
      security:
        - personalToken: []

components:
  parameters:
    GitHubUsername:
      name: "X-GitHub-Username"
      in: "header"
      required: true
      schema:
        $ref: "#/components/schemas/NonEmptyString"

    RepositoryOwner:
      name: "owner"
      in: "path"
      required: true
      schema:
        $ref: "#/components/schemas/RepositoryOwner"

    RepositoryName:
      name: "name"
      in: "path"
      required: true
      schema:
        $ref: "#/components/schemas/RepositoryName"

  responses:
    DefaultResponse:
      description: "Default error response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DefaultResponse"

    ValidationError:
      description: "Validation error response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ValidationError"

  schemas:
    AnyObject:
      type: "object"
      additionalProperties: true

    NonEmptyString:
      type: "string"
      minLength: 1

    PositiveInteger:
      type: "integer"
      format: "int64"

    RepositoryOwner:
      type: "string"
      minLength: 3

    RepositoryName:
      type: "string"
      minLength: 3

    RepositoryJob:
      type: "string"
      enum: ["test", "deploy"]

    DefaultResponse:
      type: "object"
      properties:
        detail:
          $ref: "#/components/schemas/NonEmptyString"
      required: ["detail"]

    ValidationErrorItem:
      type: "object"
      properties:
        loc:
          type: "array"
          items:
            oneOf:
              - $ref: "#/components/schemas/NonEmptyString"
              - $ref: "#/components/schemas/PositiveInteger"
          minItems: 1
        message:
          $ref: "#/components/schemas/NonEmptyString"

    ValidationError:
      type: "array"
      items:
        $ref: "#/components/schemas/ValidationErrorItem"
      minItems: 1
      uniqueItems: true

    NewRepository:
      type: "object"
      properties:
        owner:
          $ref: "#/components/schemas/NonEmptyString"
        name:
          $ref: "#/components/schemas/NonEmptyString"
      required: ["owner", "name"]

    Repository:
      type: "object"
      properties:
        uid:
          type: "string"
          format: "uuid"
        owner:
          $ref: "#/components/schemas/NonEmptyString"
        name:
          $ref: "#/components/schemas/NonEmptyString"
        jobs:
          type: "array"
          description: "List of registered jobs for the repository."
          items:
            $ref: "#/components/schemas/RepositoryJob"
          minItems: 1
        status:
          type: "string"
          enum: ["cloning", "ready", "running"]
      required: ["uid", "owner", "name", "jobs", "status"]

  securitySchemes:
    basic:
      type: "http"
      scheme: "basic"

    personalToken:
      type: "apiKey"
      in: "header"
      name: "X-GitHub-Personal-Token"

    jwt:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"

tags:
  - name: "repositories"
    description: "Repositories endpoints."

  - name: "environment"
    description: "Environment endpoints."
