defaults:
  run:
    shell: "bash"

name: "(Reusable) Verify Docs Build Well"

on:
  workflow_call:

jobs:
  build_docs:
    name: "Verify Docs Build Well"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4.1.7"

      - id: "python_and_poetry"
        uses: "./.github/actions/install_python_and_poetry"
        with:
          cache-key-suffix: "-docs"
          python-version-file: ".python-version"

      - name: "Install docs dependencies"
        run: "poetry install --only main,docs"

      - name: "Build docs"
        run: "poetry run python3 -m sphinx -b html docs/ docs/_build/"
